microsoft/iomt-fhir

deploy/scripts/Create-IomtFhirSandboxEnvironment.ps1
deploy/templates/default-azuredeploy-sandbox.json

Remove the duplicated ARM template code.

Refactor the sandbox template to reference the main template.

---

Microsoft.Health.Fhir.Ingest.sln
deploy/templates/consumption-azuredeploy.json
deploy/templates/premium-azuredeploy.json

Add an additional ARM template to host compute using Azure Function consumption plan

Add ARM template for Azure Function consumption plan

---

deploy/templates/consumption-azuredeploy.json
deploy/templates/default-azuredeploy.json
deploy/templates/premium-azuredeploy.json
src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj

Updated ARM Templates to leverage Managed Identity for NormalizeDeviceData Function.

Updated NormalizeDeviceData Function to use Managed Identity

---

Microsoft.Health.Fhir.Ingest.sln
deploy/templates/managed-identity-azuredeploy.json
src/lib/Microsoft.Health.Extensions.Fhir.R4/FhirClientFactory.cs
src/lib/Microsoft.Health.Extensions.Fhir.R4/Service/ResourceManagementService.cs
src/lib/Microsoft.Health.Extensions.Fhir/Config/FhirClientFactoryOptions.cs
src/lib/Microsoft.Health.Fhir.R4.Ingest/Host/MeasurementFhirImportExtensions.cs
src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientCreateIdentityService.cs
src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientLookupIdentityService.cs
src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientWithEncounterLookupIdentityService.cs
test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4DeviceAndPatientCreateIdentityServiceTests.cs
test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4DeviceAndPatientLookupIdentityServiceTests.cs
test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4DeviceAndPatientWithEncounterLookupIdentityServiceTests.cs

* Add configuration setting so managed identity can be used to authenticate the FHIR server.
* Add ARM template that uses managed identity.
* Move ResourceManagementService to the correct namespace.

Enable managed identity

---

src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj

… netstandard2.0 to support usage in other projects using netstandard2.0

Change target framework of Microsoft.Health.Common to netstandard2.0

---

src/func/Microsoft.Health.Fhir.Ingest.Host/IomtConnectorFunctions.cs
src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj
src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj
src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj
src/lib/Microsoft.Health.Fhir.Ingest/Service/ResourceIdentityServiceFactory.cs
src/lib/Microsoft.Health.Fhir.R4.Ingest/Host/MeasurementFhirImportExtensions.cs
src/lib/Microsoft.Health.Fhir.R4.Ingest/Microsoft.Health.Fhir.R4.Ingest.csproj

Ensure call to ResourceIdentityService isn't inlined.

Fix issue with ResourceIdentityService when in release mode

---

sample/templates/healthkitOnFhir/devicecontent.json
sample/templates/healthkitOnFhir/fhirmapping.json

Updated sample template files for HealthKitOnFhir data to support:
- Height
- Weight
- Temperature
- Blood Oxygen Saturation
- Respiratory Rate

Added support for more Healthkit data types

---

deploy/templates/consumption-azuredeploy.json
deploy/templates/default-azuredeploy-sandbox.json
deploy/templates/default-azuredeploy.json
deploy/templates/managed-identity-azuredeploy.json
deploy/templates/premium-azuredeploy.json
docs/ARMInstallation.md
docs/ARMInstallationManagedIdentity.md
docs/Sandbox.md

* Update the template label.
* Update the customer facing document.
* Tested: 
- ARM deployment
- Sandbox
- Docker

Update the "ResourceIdentityServiceType" to "ResourceIdentityResolutionType"

---

src/lib/Microsoft.Health.Fhir.Ingest/Template/FhirTemplateProcessor.cs
src/lib/Microsoft.Health.Fhir.R4.Ingest/Template/CodeValueFhirTemplateProcessor.cs
test/Microsoft.Health.Fhir.Ingest.UnitTests/Template/FhirTemplateProcessorTests.cs

Fix name of method in FhirTemplateProcessor

---

docs/Sandbox.md

Adding disclaimer per discussion.

Adding IoT Central Data Export (legacy) note

---

docs/Configuration.md
test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/IotCentralJsonPathContentTemplateTests.cs
test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_CollectionContentTemplateMixedValidity.json
test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_IotCentralPayloadExample.json

Also adding additional unit tests
[AB#76200](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/76200)

Updating docs to include reference to IotCentralJsonPathContentTemplate

---

test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/NormalizationTests.cs
test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_CollectionContentTemplateHrAndSteps.json

Add normalization tests based off of JsonPath templates to cover filter and projection scenarios

Add normalization tests based off of JsonPath templates

---

sample/templates/healthkitOnFhir/devicecontent.json
sample/templates/healthkitOnFhir/fhirmapping.json

Updated mappings to support new types supported by HealthKitOnFhir library.
- HKQuantityTypeIdentifierRestingHeartRate
- HKQuantityTypeIdentifierHeartRateVariabilitySDNN
- HKQuantityTypeIdentifierWalkingHeartRateAverage
- HKQuantityTypeIdentifierAppleExerciseTime
- HKQuantityTypeIdentifierAppleStandTime
- HKQuantityTypeIdentifierActiveEnergyBurned
- HKQuantityTypeIdentifierEnvironmentalAudioExposure
- HKQuantityTypeIdentifierDietaryEnergyConsumed

Updated HelathKitOnFhir mappings to support more types

---

README.md
deploy/templates/managed/azuredeploy.json
deploy/templates/managed/azuredeploy.parameters.json

Staging this PR, when we release the the mapping manager.

reference for the mapping manager, and adding managed arm template

---

tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/package.json

Update the package.json with dependency explicitly.

Call out the version explicitly.

---

src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj
src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj
src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj
src/lib/Microsoft.Health.Extensions.Fhir.R4/Microsoft.Health.Extensions.Fhir.R4.csproj
src/lib/Microsoft.Health.Extensions.Fhir/Microsoft.Health.Extensions.Fhir.csproj
src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj
src/lib/Microsoft.Health.Fhir.Ingest.Template/Microsoft.Health.Fhir.Ingest.Template.csproj
src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj
src/lib/Microsoft.Health.Fhir.R4.Ingest/Microsoft.Health.Fhir.R4.Ingest.csproj
src/lib/Microsoft.Health.Logger/Microsoft.Health.Logging.csproj
test/Microsoft.Health.Common.UnitTests/Microsoft.Health.Common.UnitTests.csproj
test/Microsoft.Health.Events.UnitTest/Microsoft.Health.Events.UnitTest.csproj
test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/Microsoft.Health.Extensions.Fhir.R4.UnitTests.csproj
test/Microsoft.Health.Extensions.Fhir.UnitTests/Microsoft.Health.Extensions.Fhir.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/Microsoft.Health.Fhir.Ingest.Template.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.UnitTests/Microsoft.Health.Fhir.Ingest.UnitTests.csproj
test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Microsoft.Health.Fhir.R4.Ingest.UnitTests.csproj
test/Microsoft.Health.Tests.Common.R4/Microsoft.Health.Tests.Common.R4.csproj
test/Microsoft.Health.Tests.Common/Microsoft.Health.Tests.Common.csproj
tools/data-mapper/Microsoft.Health.Tools.DataMapper/Microsoft.Health.Tools.DataMapper.csproj

Ensure System.Text.Encodings.Web 5.0.1 is used for required packages

Upgrade OSS Packages

---

tools/data-mapper/Microsoft.Health.Tools.DataMapper/Microsoft.Health.Tools.DataMapper.csproj
tools/data-mapper/README.md

Updated the data-mapper tool to dotnet 6.

Updated data-mapper to dotnet 6

---

src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj

Updating Azure.Messaging.EventHubs nuget package to latest 5.6.2

Update EventHubs nuget package to ver 5.6.2

---

README.md
deploy/scripts/Create-IomtFhirSandboxEnvironment.ps1
deploy/scripts/Create-IomtWebJobsEnvironment.ps1
deploy/templates/consumption-azuredeploy.json
deploy/templates/default-azuredeploy-sandbox.json
deploy/templates/default-azuredeploy-webjobs.json
deploy/templates/default-managed-identity-azuredeploy.json
deploy/templates/premium-azuredeploy.json
docs/ARMInstallation.md
tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/Detail.Forms.Tutorials.tsx
tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/List.Modals.Import.tsx
tools/data-mapper/README.md

Pointed scripts, ARM templates, and docs to the main branch because the default branch "master" has been renamed to "main".

Updating to main branch

---

src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj
src/lib/Microsoft.Health.Extensions.Fhir/Microsoft.Health.Extensions.Fhir.csproj
src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj
src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj
test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/IotJsonPathContentTemplateTests.cs

This PR updates several projects to only target netstandard2.0.

Removing multi target projects

---

src/lib/Microsoft.Health.Common/DependencyInjection/IServiceCollectionExtensions.cs
src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj

This PR includes an IServiceCollection extension that simplifies binding environment variables to classes. Adding this to the Microsoft.Health.Common package for use in several projects.

Added IConfiguration dependency injection extension

---

src/console/Normalize/Processor.cs
src/console/Startup.cs
src/lib/Microsoft.Health.Extensions.Host/ConfigurationExtensions.cs
src/lib/Microsoft.Health.Fhir.Ingest/Host/DeviceDataNormalizationExtensions.cs

* Enhance DI helpers for Normalization to support IServiceCollection.
* Add new NormalizationExceptionTelemetryProcessor logic to Console Processor and add necessary DI.

Add new NormalizationExceptionTelemetryProcessor logic to Console Processor

---

src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj
src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj
src/lib/Microsoft.Health.Expressions/Microsoft.Health.Expressions.csproj
src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj
src/lib/Microsoft.Health.Fhir.Ingest.Template/Microsoft.Health.Fhir.Ingest.Template.csproj
src/lib/Microsoft.Health.Fhir.Ingest.Validation/Microsoft.Health.Fhir.Ingest.Validation.csproj
src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj
src/lib/Microsoft.Health.Fhir.R4.Ingest/Microsoft.Health.Fhir.R4.Ingest.csproj
src/lib/Microsoft.Health.Logger/Microsoft.Health.Logging.csproj
test/Microsoft.Health.Fhir.Ingest.UnitTests/Microsoft.Health.Fhir.Ingest.UnitTests.csproj
test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Microsoft.Health.Fhir.R4.Ingest.UnitTests.csproj
test/Microsoft.Health.Tests.Common.R4/Microsoft.Health.Tests.Common.R4.csproj
test/Microsoft.Health.Tests.Common/Microsoft.Health.Tests.Common.csproj

Consolidate mismatched Nuget versions in the solution

Update Newtonsoft.Json to 13.0.1

---

src/lib/Microsoft.Health.Fhir.Ingest/Service/NormalizationEventConsumerService.cs
src/lib/Microsoft.Health.Logger/Telemetry/ITimed.cs
src/lib/Microsoft.Health.Logger/Telemetry/TelemetryExtensions.cs
src/lib/Microsoft.Health.Logger/Telemetry/TimedExtensions.cs

Added ITimed with extension support to track call durations and emit to metrics.

Add ability to easily track call duration and emit to a metric

---

src/console/Microsoft.Health.Fhir.Ingest.Console.csproj
src/console/Program.cs
src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj
src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj
src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj
src/lib/Microsoft.Health.Expressions/Microsoft.Health.Expressions.csproj
src/lib/Microsoft.Health.Extensions.Fhir.R4/Microsoft.Health.Extensions.Fhir.R4.csproj
src/lib/Microsoft.Health.Extensions.Fhir.R4/Service/FhirService.cs
src/lib/Microsoft.Health.Extensions.Fhir/Microsoft.Health.Extensions.Fhir.csproj
src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj
src/lib/Microsoft.Health.Fhir.Ingest.Schema/Microsoft.Health.Fhir.Ingest.Schema.csproj
src/lib/Microsoft.Health.Fhir.Ingest.Template/Microsoft.Health.Fhir.Ingest.Template.csproj
src/lib/Microsoft.Health.Fhir.Ingest.Validation/Microsoft.Health.Fhir.Ingest.Validation.csproj
src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj
src/lib/Microsoft.Health.Fhir.R4.Ingest.Templates/Microsoft.Health.Fhir.R4.Ingest.Templates.csproj
src/lib/Microsoft.Health.Fhir.R4.Ingest/Microsoft.Health.Fhir.R4.Ingest.csproj
src/lib/Microsoft.Health.Logger/Microsoft.Health.Logging.csproj
test/Microsoft.Health.Common.UnitTests/Microsoft.Health.Common.UnitTests.csproj
test/Microsoft.Health.Events.UnitTest/Microsoft.Health.Events.UnitTest.csproj
test/Microsoft.Health.Expressions.UnitTests/Microsoft.Health.Expressions.UnitTests.csproj
test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/Microsoft.Health.Extensions.Fhir.R4.UnitTests.csproj
test/Microsoft.Health.Extensions.Fhir.UnitTests/Microsoft.Health.Extensions.Fhir.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/Microsoft.Health.Fhir.Ingest.Template.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.UnitTests/Microsoft.Health.Fhir.Ingest.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.Validation.UnitTests/Microsoft.Health.Fhir.Ingest.Validation.UnitTests.csproj
test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Microsoft.Health.Fhir.R4.Ingest.UnitTests.csproj
test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4FhirHealthServiceTests.cs
test/Microsoft.Health.Tests.Common.R4/Microsoft.Health.Tests.Common.R4.csproj
test/Microsoft.Health.Tests.Common/Microsoft.Health.Tests.Common.csproj

Update packages to latest except Azure Web Job related packages due to backwards compatibility issues.

Update Solution Nuget Packages

---

src/console/Microsoft.Health.Fhir.Ingest.Console.csproj
src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj
test/Microsoft.Health.Common.UnitTests/Microsoft.Health.Common.UnitTests.csproj
test/Microsoft.Health.Events.UnitTest/Microsoft.Health.Events.UnitTest.csproj
test/Microsoft.Health.Expressions.UnitTests/Microsoft.Health.Expressions.UnitTests.csproj
test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/Microsoft.Health.Extensions.Fhir.R4.UnitTests.csproj
test/Microsoft.Health.Extensions.Fhir.UnitTests/Microsoft.Health.Extensions.Fhir.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/Microsoft.Health.Fhir.Ingest.Template.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.UnitTests/Microsoft.Health.Fhir.Ingest.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.Validation.UnitTests/Microsoft.Health.Fhir.Ingest.Validation.UnitTests.csproj
test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Microsoft.Health.Fhir.R4.Ingest.UnitTests.csproj
test/Microsoft.Health.Tests.Common.R4/Microsoft.Health.Tests.Common.R4.csproj
test/Microsoft.Health.Tests.Common/Microsoft.Health.Tests.Common.csproj

Ensure Newtonsoft 13.0.1+ is used in test projects
Ensure Azure.Storage.Queues 12.11+ is used
Update LangVersion to 10.0 in relevant projects

Package Updates 8/3/2022

---

src/console/Microsoft.Health.Fhir.Ingest.Console.csproj
src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj
tools/data-mapper/Microsoft.Health.Tools.DataMapper/Microsoft.Health.Tools.DataMapper.csproj

Prior commit updated the wrong project.  The vulnerability is in the Function app project, not the console app.

Personal/duburson/cgalert CVE 2021 24112

---

tools/data-mapper/Microsoft.Health.Tools.DataMapper/Microsoft.Health.Tools.DataMapper.csproj

Addresses component governance alert CVE-2022-41032 in NuGet.Protocol 5.11.0. Severity: High

Update nuget packages in DataMapper

---

src/console/Microsoft.Health.Fhir.Ingest.Console.Common/Microsoft.Health.Fhir.Ingest.Console.Common.csproj
src/console/Microsoft.Health.Fhir.Ingest.Console.csproj
src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj
src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj
src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj
src/lib/Microsoft.Health.Expressions/Microsoft.Health.Expressions.csproj
src/lib/Microsoft.Health.Extensions.Fhir.R4/Microsoft.Health.Extensions.Fhir.R4.csproj
src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj
src/lib/Microsoft.Health.Fhir.Ingest.Legacy/Microsoft.Health.Fhir.Ingest.Legacy.csproj
src/lib/Microsoft.Health.Fhir.Ingest.Template/Microsoft.Health.Fhir.Ingest.Template.csproj
src/lib/Microsoft.Health.Fhir.Ingest.Validation/Microsoft.Health.Fhir.Ingest.Validation.csproj
src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj
src/lib/Microsoft.Health.Fhir.R4.Ingest/Microsoft.Health.Fhir.R4.Ingest.csproj
test/Microsoft.Health.Common.UnitTests/Microsoft.Health.Common.UnitTests.csproj
test/Microsoft.Health.Events.UnitTest/Microsoft.Health.Events.UnitTest.csproj
test/Microsoft.Health.Expressions.UnitTests/Microsoft.Health.Expressions.UnitTests.csproj
test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/Microsoft.Health.Extensions.Fhir.R4.UnitTests.csproj
test/Microsoft.Health.Extensions.Fhir.UnitTests/Microsoft.Health.Extensions.Fhir.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.Legacy.UnitTests/Microsoft.Health.Fhir.Ingest.Legacy.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/Microsoft.Health.Fhir.Ingest.Template.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.UnitTests/Microsoft.Health.Fhir.Ingest.UnitTests.csproj
test/Microsoft.Health.Fhir.Ingest.Validation.UnitTests/Microsoft.Health.Fhir.Ingest.Validation.UnitTests.csproj
test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Microsoft.Health.Fhir.R4.Ingest.UnitTests.csproj
test/Microsoft.Health.Tests.Common.R4/Microsoft.Health.Tests.Common.R4.csproj
test/Microsoft.Health.Tests.Common/Microsoft.Health.Tests.Common.csproj
tools/mapping-generator/Microsoft.Health.Fhir.Ingest.Template.Generator.Tests/Microsoft.Health.Fhir.Ingest.Template.Generator.UnitTests.csproj
tools/mapping-generator/Microsoft.Health.Fhir.Ingest.Template.Generator/Microsoft.Health.Fhir.Ingest.Template.Generator.csproj

Update Azure.* packages to latest
Update Newtonsoft package version
Update Polly package version

Update Packages to latest

---

src/lib/Microsoft.Health.Fhir.Ingest/Service/ResourceIdentityServiceFactory.cs
test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/ResourceIdentityServiceFactoryTests.cs

Update parsing of ResourceIdentityServiceType value to be case insensitive.
To support create and Create or lookup and Lookup

Update parsing of ResourceIdentityServiceType value to be case insensitive.

---

deploy/templates/bicep/ContainerApp-SingleAzureDeploy.json
docs/BicepInstallation.md

- generated an ARM template from the entry Bicep template (ContainerApp-SingleAzureDeploy.bicep) using the az bicep build command 
- created a Deploy to Azure button using remote generated ARM template 
- added documentation for Deploy to Azure button 
- added fhirVersion as a parameter in documentation of other deployment options

Add Deploy to Azure button as a deployment option 
