microsoft/iomt-fhir

src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs
The FHIR Server may respond with either a 409 Conflict or a 412 Precondition Failed if a PUT operation is performed on an Observation Resource and the Version Id is not identical. The current code handles 409 but not 412.
This pull request includes:
- Support for handling a 412 response.
- Updating retry logic to happen 2 times (3 attempts total) if a update fails because of a version conflict.
- A fix that was causing exceptions that happened while trying to update an Observation to be 'swallowed'.
=> Fixed issue where observation version conflicts weren't always handled

.gitignore, src/lib/Microsoft.Health.Extensions.Fhir.R4/BundleExtensions.cs, src/lib/Microsoft.Health.Extensions.Fhir.R4/Service/ResourceManagementService.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs, test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/BundleExtensionsTests.cs, test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/Microsoft.Health.Extensions.Fhir.R4.UnitTests.csproj, test/Microsoft.Health.Fhir.Ingest.UnitTests/Data/EventDataWithJsonBodyToJTokenConverterTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Template/CodeValueFhirTemplateFactoryTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Template/CollectionContentTemplateFactoryTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Template/CollectionFhirTemplateFactoryTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Template/IotJsonPathContentTemplateFactoryTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Template/IotJsonPathContentTemplateTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Template/JsonContentTemplateFactoryTests.cs
A condition exists, where, a search request can return an empty bundle with a continuation token. The ReadOneFromBundle method assumed that if any Resource meeting the search criteria was found, the first bundle returned would contain at least one resource.
These changes include:
- A fix to ensure the continuation token is respected.
- Fixes to unit tests so they can be run on Linux and Mac machines.
- An update to the .gitignore file to ignore Mac OS system files.
=> Fixed issue where bundle extension could return null when resource exists

deploy/templates/default-azuredeploy-sandbox.json
The Sandbox ARM template would set Audience in the authentication settings to "https://azurehealthcareapis.com" instead of "https://{SERVICE_NAME}.azurehealthcareapis.com". This causes tokens issued to the service client application to be denied access to the FHIR Server.
=> Fixed issue that caused token audience to be incorrect

deploy/scripts/Create-IomtFhirSandboxEnvironment.ps1, deploy/templates/default-azuredeploy-sandbox.json
In fixing the FHIR server audience previously for SMART on FHIR apps, a second place was missed, causing a mismatch that didn't allow the sandbox connector to write into the FHIR server. Both the Connector and the FHIR server now use the same parameter, and the fixed audience is passed in on that parameter.
=> Fix a mismatch in the FHIR  server audience in the sandbox deployment

deploy/templates/consumption-azuredeploy.json, deploy/templates/default-azuredeploy-sandbox.json, deploy/templates/default-azuredeploy.json, deploy/templates/premium-azuredeploy.json
Remove default value from ARM template resource location. Function didn't work as intended and prevented field from showing as required in template editor.
#27
=> Remove default value from ARM template resource location

README.md, docs/ARMInstallationManagedIdentity.md
Adding documentation for installing the connector using managed identity to connect to Azure API for FHIR, including the "easy button"
=> Add document for deploying managed identity

src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/ExceptionTelemetryProcessor.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Telemetry/ExceptionTelemetryProcessorTests.cs
When a FhirMappingTemplate isn't found it currently causes an internal server error and prevents the stream analytics job from proceeding.  Change behavior to capture exception and report as telemetry.
=> Include TemplateNotFound in the handled exceptions

DockerRun.ps1, Dockerfile, deploy/docker/DockerRun.ps1, src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj, src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj, src/lib/Microsoft.Health.Extensions.Fhir.R4/Microsoft.Health.Extensions.Fhir.R4.csproj, src/lib/Microsoft.Health.Extensions.Fhir/Microsoft.Health.Extensions.Fhir.csproj, src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj, src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj, src/lib/Microsoft.Health.Fhir.R4.Ingest/Microsoft.Health.Fhir.R4.Ingest.csproj, test/Microsoft.Health.Common.UnitTests/Microsoft.Health.Common.UnitTests.csproj, test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/Microsoft.Health.Extensions.Fhir.R4.UnitTests.csproj, test/Microsoft.Health.Extensions.Fhir.UnitTests/Microsoft.Health.Extensions.Fhir.UnitTests.csproj, test/Microsoft.Health.Fhir.Ingest.UnitTests/Microsoft.Health.Fhir.Ingest.UnitTests.csproj, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Microsoft.Health.Fhir.R4.Ingest.UnitTests.csproj, test/Microsoft.Health.Tests.Common/Microsoft.Health.Tests.Common.csproj
This PR may be controversial since it requires some package references to be updated.
"Microsoft.Net.Compilers" was changed to "Microsoft.Net.Compilers.Toolset" since only the Toolset can successfully compile for Linux. 
"Microsoft.Net.Compilers" also appeared to be deprecated, so we should probably migrate off of it anyway. https://github.com/dotnet/roslyn/issues/40129#issuecomment-565661236
The controversial part is that switching to Microsoft.Net.Compilers.Toolset seems to require Microsoft.NET.Sdk.Functions to be upgraded and TargetFramework to be updated to 3.1
=> support docker containers for functions code

Dockerfile, deploy/docker/DockerRun.ps1, deploy/scripts/Create-IomtFhirSandboxEnvironment.ps1, deploy/templates/consumption-azuredeploy.json, deploy/templates/default-azuredeploy-sandbox.json, deploy/templates/default-azuredeploy.json, deploy/templates/managed-identity-azuredeploy.json, deploy/templates/premium-azuredeploy.json, docs/ARMInstallation.md, docs/ARMInstallationManagedIdentity.md, docs/Debugging.md, docs/Sandbox.md, docs/local.settings.json, src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj
Add FHIR versioning handling strategy to take its selection in template from customer, as well as update the instruction documents.
Test Result
| Support | Test Result |
|-|-|
| Managed identity deployment | Succeeded |
| Un-managed identity deployment | Succeeded |
| Sandbox deployment | Succeeded |
| Docker | Succeeded |
| Local VS | Succeeded |
=> Add FHIR versioning handling strategy to take its selection in template from customer, as well as update the instruction documents.

deploy/templates/managed-identity-azuredeploy.json
Add optional audience to managed identity template.  Update default if not set to FHIR service URL to match current default audience on the Azure API for FHIR.
=> Update audience in Managed Identity ARM template

deploy/templates/consumption-azuredeploy.json, deploy/templates/default-azuredeploy-sandbox.json, deploy/templates/default-azuredeploy.json, deploy/templates/managed-identity-azuredeploy.json, deploy/templates/premium-azuredeploy.json, docs/ARMInstallation.md, docs/ARMInstallationManagedIdentity.md, docs/Debugging.md, docs/Sandbox.md, docs/local.settings.json, src/lib/Microsoft.Health.Fhir.Ingest/Config/ResourceIdentityOptions.cs, src/lib/Microsoft.Health.Fhir.Ingest/Config/ResourceIdentityServiceType.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/ResourceIdentityServiceAttribute.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/ResourceIdentityServiceFactory.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Host/MeasurementFhirImportExtensions.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientCreateIdentityService.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientLookupIdentityService.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientWithEncounterLookupIdentityService.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/ResourceIdentityServiceFactoryTests.cs
- Add the Assembly attribute to register the implementation classes.
- Use structured enum data type for ResourceIdentityServiceType.
- Update Unit Tests with new enum type.
=> Update the resource identity service type with Assembly attribute and short names

deploy/templates/consumption-azuredeploy.json, deploy/templates/default-azuredeploy.json, deploy/templates/managed-identity-azuredeploy.json, deploy/templates/premium-azuredeploy.json
Corrected a secret name in the ARM templates to use key_vault_name instead of storage_account_name (this bug is only apparent if you further modify the ARM templates to use different values for key_vault_name and storage_account_name).
=> Corrected secret name in ARM templates

.gitignore, src/lib/Microsoft.Health.Fhir.Ingest.Template/CollectionContentTemplateFactory.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/IotCentralJsonPathContentTemplate.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/IotCentralJsonPathContentTemplateFactory.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/IotCentralJsonPathContentTemplateFactoryTests.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/IotCentralJsonPathContentTemplateTests.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/Microsoft.Health.Fhir.Ingest.Template.UnitTests.csproj, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_IotCentralJsonPathContentTemplateInvalidMissingTypeMetadata.json, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_IotCentralJsonPathContentTemplateInvalidMissingValueField.json, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_IotCentralJsonPathContentTemplateValid.json, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_IotCentralJsonPathContentTemplateValidWithOptional.json, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_IotCentralPayloadExample.json
IoT Central has an updated [telemetry format](https://github.com/microsoft/iomt-fhir/pull/new/personal/rogordon01/addIotCentralTemplateFactory) for exporting device data. This PR creates a new template factory in order to normalize events of this type.
=> Create a new template factory for IoT Central

deploy/templates/managed-identity-azuredeploy.json
This pull request refactors the managed identity ARM template used to deploy the IoMT-connector to expose the names of the EventHubs used for ingestion as well as the hostname of the EventHub namespace that hosts those EventHubs. This change enables consumers of the template to set up RBAC roles and connect to the ingestion EventHubs without making assumptions about naming patterns used in the ARM template.
To facilitate the refactor, this pull request also pulls out the constants `normalizeddata` and `devicedata` into template variables and updates the template to reference the variables instead of repeating the constants in multiple places. As such, if in the future the naming patters were to change, the strings can simply be updated in one location.
cc @alexgolesh @wkilday
=> Add EventHub connection info to deployment outputs

src/console/Microsoft.Health.Fhir.Ingest.Console.csproj, src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj, src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj, src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj, src/lib/Microsoft.Health.Extensions.Fhir.R4/Microsoft.Health.Extensions.Fhir.R4.csproj, src/lib/Microsoft.Health.Extensions.Fhir/Microsoft.Health.Extensions.Fhir.csproj, src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj, src/lib/Microsoft.Health.Fhir.Ingest.Schema/Microsoft.Health.Fhir.Ingest.Schema.csproj, src/lib/Microsoft.Health.Fhir.Ingest.Template/Microsoft.Health.Fhir.Ingest.Template.csproj, src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj, src/lib/Microsoft.Health.Fhir.R4.Ingest/Microsoft.Health.Fhir.R4.Ingest.csproj, src/lib/Microsoft.Health.Logger/Microsoft.Health.Logging.csproj
The .NET SDK prevents test projects from being packable. When we took a dependency on xunit recently in some of our *.csproj files, this made some of our projects unable to be packed. To make a project packable again we have to explicitly allow packing. This PR enables our non-test code to be packable.
=> Enable NuGet package creation

deploy/templates/consumption-azuredeploy.json, deploy/templates/default-azuredeploy.json, deploy/templates/managed-identity-azuredeploy.json, deploy/templates/premium-azuredeploy.json, src/console/Microsoft.Health.Fhir.Ingest.Console.csproj, src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj, src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj, src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj, src/lib/Microsoft.Health.Extensions.Fhir.R4/Microsoft.Health.Extensions.Fhir.R4.csproj, src/lib/Microsoft.Health.Extensions.Fhir/Microsoft.Health.Extensions.Fhir.csproj, src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj, src/lib/Microsoft.Health.Fhir.Ingest.Schema/Microsoft.Health.Fhir.Ingest.Schema.csproj, src/lib/Microsoft.Health.Fhir.Ingest.Template/Microsoft.Health.Fhir.Ingest.Template.csproj, src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj, src/lib/Microsoft.Health.Fhir.Ingest/Service/ResourceIdentityServiceFactory.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Microsoft.Health.Fhir.R4.Ingest.csproj, src/lib/Microsoft.Health.Logger/Microsoft.Health.Logging.csproj, test/Microsoft.Health.Common.UnitTests/Microsoft.Health.Common.UnitTests.csproj, test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/Microsoft.Health.Extensions.Fhir.R4.UnitTests.csproj, test/Microsoft.Health.Extensions.Fhir.UnitTests/Microsoft.Health.Extensions.Fhir.UnitTests.csproj, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/Microsoft.Health.Fhir.Ingest.Template.UnitTests.csproj, test/Microsoft.Health.Fhir.Ingest.UnitTests/Microsoft.Health.Fhir.Ingest.UnitTests.csproj, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Microsoft.Health.Fhir.R4.Ingest.UnitTests.csproj, test/Microsoft.Health.Tests.Common.R4/Microsoft.Health.Tests.Common.R4.csproj, test/Microsoft.Health.Tests.Common/Microsoft.Health.Tests.Common.csproj
Recent package upgrade accidently included a .NET 5 package upgrade.  Because App Services aren't yet upgraded to .NET 5 loading framework dependencies causes the application to crash.
* Fix Microsoft.Extensions.Options incorrectly upgraded to 5.0.0 (set to version 3.1.12).
* Fix XUnit dependencies added to non test projects.
* Update packages to max .NET 3.0 version where available.
* Update API version and principal types for the Event Hub Role assignments per suggested changes in https://github.com/microsoft/iomt-fhir/pull/79
=> Fix Function App unable to start

src/console/Startup.cs, src/lib/Microsoft.Health.Events/EventCheckpointing/ICheckpointClient.cs, src/lib/Microsoft.Health.Events/EventCheckpointing/StorageCheckpointClient.cs, src/lib/Microsoft.Health.Events/EventCheckpointing/StorageCheckpointOptions.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/EventProcessor.cs, test/Microsoft.Health.Events.UnitTest/StorageCheckpointTests.cs
Description -
When customer changes their source of events (source event hub) the IoT Connector watermark should be reset and process all data available from the earliest available point in the event hub.
Changes - 
* Append event hub name to the checkpoint blob path
* Delete checkpoints corresponding to an older source event hub
* Note - This change is applicable to the event hubs for both the app types (i.e. watermarks will be handled in the same fashion for input event hub or the normalization event hub, but they are independently maintained.)
Testing - 
* Manual testing by running the Fhir.Ingest console app and verifying the various scenarios
- Change event hub namespace
- Change event hub within the same event hub namespace
- Same event hub
* Added UTs for reset checkpoints
PENDING …
=> Clear Event Hub Device Watermarks when source event hub changed

sample/templates/sandbox/devicecontent.json, sample/templates/sandbox/legacy/devicecontent.json, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/CodeValueFhirTemplateFactoryTests.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/CollectionFhirTemplateFactoryTests.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/NormalizationTests.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_CodeValueFhirTemplate_Components.json, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_CodeValueFhirTemplate_Quantity.json, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_CollectionContentTemplateMultipleIotCentralJsonPath.json, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/TestInput/data_CollectionFhirTemplateMixedValidity.json
'typeName' attribute was misaligned between the sandbox devicecontent.json and fhirmapping.json (bp vs bloddpressure).
As a result, bloodpressure data wasn't propagated to the fhir server.
Replaced the usage of 'bp' in favor or 'bloodpressure', in production code, as well as in tests for the sake of conformity.
=> Align Blood Pressure typeNames

src/lib/Microsoft.Health.Extensions.Fhir.R4/ModelExtensions.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientLookupIdentityService.cs, test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/ModelExtensionsTests.cs, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4DeviceAndPatientLookupIdentityServiceTests.cs
Validates that the relative reference patient identifier does not contain any URI restricted characters.
If the patient identifier contains restricted URI characters, then we log a `NotSupportedException`. We want to to this validation up front because the subsequent calls to FHIR will fail and we want to make it clear that the failure occurred due to certain characters contained in the identifier.
=> Validate patient id is a relative reference

src/console/Normalize/Processor.cs
There is an extra `foreach `statement that ends up copying Properties into the eventData object twice. The extra `foreach` should be removed.
```
foreach (KeyValuePair<string, object> entry in x.Properties)
{
eventData.Properties[entry.Key] = entry.Value;
}
foreach (KeyValuePair<string, object> entry in x.SystemProperties)
{
eventData.SystemProperties.TryAdd(entry.Key, entry.Value);
}
foreach (KeyValuePair<string, object> entry in x.Properties)
{
eventData.Properties[entry.Key] = entry.Value;
}
```
=> Remove extra "foreach" when creating EventData object

src/console/MeasurementCollectionToFhir/Processor.cs, src/console/Normalize/Processor.cs, src/console/Startup.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/EventConsumerService.cs, src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj, test/Microsoft.Health.Events.UnitTest/EventConsumerServiceTests.cs
Currently, when an event incurs an error the entire batch is retried forever. This PR utilizes `Polly` to perform the retry logic. Only a specific set of exceptions will be allowed to retry.
=> Use Polly to perform retries on failed event processing

src/lib/Microsoft.Health.Common/Telemetry/Metrics/Dimensions/ErrorType.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/EventProcessor.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/EventHubErrorCode.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/EventHubExceptionTelemetryProcessor.cs, src/lib/Microsoft.Health.Events/Telemetry/Metrics/EventMetrics.cs, test/Microsoft.Health.Events.UnitTest/EventHubExceptionTelemetryProcessorTests.cs
Bug: Upon handling errors when processing events, the corresponding exception was always being cast to EventHubException even when the exception was not of that type causing an invalid cast exception in the error handling and as a result no errors/metrics were being logged.
Fix: Process the exception according to its type.
=> Handle event processing exceptions based on type.

tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/package.json, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/Constants.ts, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/Detail.Forms.Tutorials.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/Detail.Widgets.Test.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/Detail.css, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/jsonlint-mod.d.ts, tools/data-mapper/Microsoft.Health.Tools.DataMapper/Controllers/Apis/Utility.cs
Updated the IoMT Connector Data Mapper as follows:
- Replaced Newtonsoft.Json with System.Text.Json to validate JSON syntax when testing normalization and FHIR transformation. System.Text.Json is used because it follows RFC 8259 specification, which, for example, does not allow trailing commas.
- Use JSON Lint to validate JSON syntax as device data sample is input, and display validation result. JSON Lint is used because it considers trailing commas as invalid and it provides an error message with the line number of the error.
- Use CodeMirror as the editor for device data sample to improve the experience of entering the JSON and of finding JSON validation errors.
- Corrected spelling in Device Mapping tutorial.
=> Data Mapper: JSON validation of Device Data Sample

tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/package.json
Moved `react-scripts` in `package.json` from `dependencies` to `devDependencies` to remove `npm audit` warnings about vulnerabilities that are false positives, as detailed in https://github.com/facebook/create-react-app/issues/11092 and https://github.com/facebook/create-react-app/issues/11174.
The affected components (packages) mentioned in these warnings are development-only dependencies.
=> Removal of false positive 'npm audit' warnings

tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/package.json, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/App.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/Constants.ts, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/NavMenu.css, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/NavMenu.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/Detail.Forms.Tutorials.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/Detail.Widgets.Device.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/Detail.Widgets.Fhir.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/List.Modals.Creation.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/List.Modals.Export.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/List.Modals.Name.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/List.Page.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/services/PersistService.ts, tools/data-mapper/Microsoft.Health.Tools.DataMapper/Microsoft.Health.Tools.DataMapper.csproj
Updated the IoMT Connector Data Mapper as follows:
- Enabled renaming a mapping's type name on the home page (containing the list of mappings) and on the mapping page, as shown in the following screenshots.
- "Rename" option on home page:
- "Rename" option on mapping page:
- Pressing "Rename" from the home page or mapping page opens this dialog, which is pre-filled with the current type name:
- Note: Empty type names are not allowed anymore:
- Also updated reference to Heart Rate (from Blood Pressure) in tutorial:
=> Data Mapper: Editing type name

src/lib/Microsoft.Health.Common/Telemetry/IomtException.cs, src/lib/Microsoft.Health.Common/Telemetry/IomtTelemetryFormattableException.cs, src/lib/Microsoft.Health.Common/Telemetry/Metrics/Dimensions/DimensionNames.cs, src/lib/Microsoft.Health.Common/Telemetry/Metrics/Dimensions/ErrorSource.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/EventHubConfigurationExceptionTelemetryProcessor.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/EventHubErrorCode.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/EventHubExceptionTelemetryProcessor.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/InvalidEventHubException.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/UnauthorizedAccessEventHubException.cs, test/Microsoft.Health.Events.UnitTest/EventHubConfigurationExceptionTelemetryProcessorTests.cs, test/Microsoft.Health.Events.UnitTest/EventHubExceptionTelemetryProcessorTests.cs
Added custom exceptions for the following scenarios:
- Event Hub not configured (e.g. Namespace/FQDN, name, or consumer group is incorrect)
- Event Hub access not authorized (e.g. Azure Event Hubs Data Receiver role is missing)
=> Customized Event Hub configuration exceptions

src/console/MeasurementCollectionToFhir/Processor.cs, src/console/Normalize/Processor.cs, src/lib/Microsoft.Health.Common/Telemetry/Exceptions/IomtTelemetryFormattableException.cs, src/lib/Microsoft.Health.Common/Telemetry/MetricExtension.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/InvalidEventHubException.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/UnauthorizedAccessEventHubException.cs, src/lib/Microsoft.Health.Events/Telemetry/Metrics/EventMetrics.cs, src/lib/Microsoft.Health.Extensions.Fhir.R4/BundleExtensions.cs, src/lib/Microsoft.Health.Extensions.Fhir.R4/Telemetry/Metrics/FhirClientMetrics.cs, src/lib/Microsoft.Health.Extensions.Fhir/MultipleResourceFoundException.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/TemplateNotFoundException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Data/CorrelationIdNotDefinedException.cs, src/lib/Microsoft.Health.Fhir.Ingest/FhirResourceNotFoundException.cs, src/lib/Microsoft.Health.Fhir.Ingest/ResourceIdentityNotDefinedException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/PatientDeviceMismatchException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/Metrics/IomtMetrics.cs
Changes include:
* minor refactor to have a common method create the error metric so that the metric definition is consistent.
* update InvalidEventHubException and EventHubUnauthorizedAccessException to Critical severity
* update other custom exceptions to use IomtTelemetryFormattableException
=> refactor: Consolidate creation of error metric 

src/lib/Microsoft.Health.Fhir.Ingest/InvalidQuantityFhirValueException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/FhirExceptionTelemetryProcessor.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Template/QuantityFhirValueProcessor.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Telemetry/FhirExceptionTelemetryProcessorTests.cs, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Template/QuantityFhirValueProcessorTests.cs
Bug: QuantityFhirValueProcessor format exceptions cause connector to spin on bad data
Issue: When an invalid data value such as "NaN" is passed as a QuantityFhirValue, we are unable to parse it to decimal and the exception thrown is not handled, causing the processor to continuously retry on this exception.
Fix: Add custom exception for invalid data quantity type values. Throw this custom exception for invalid data and add it to the list of handleable FHIR exceptions that will just log the associated error metric and continue processing subsequent event batches.
Note: This PR is currently based off of a refactor PR - https://github.com/microsoft/iomt-fhir/pull/145
=> fix: QuantityFhirValueProcessor format exceptions cause connector to spin on bad data

src/console/Normalize/Processor.cs, src/func/Microsoft.Health.Fhir.Ingest.Host/IomtConnectorFunctions.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/IncompatibleDataException.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/MeasurementExtractor.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementEventNormalizationService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/NormalizationExceptionTelemetryProcessor.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/CalculatedFunctionContentTemplateConfigurationTests.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/CalculatedFunctionContentTemplateTests.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/JsonPathContentTemplateTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/MeasurementEventNormalizationServiceTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Telemetry/NormalizationExceptionTelemetryProcessorTests.cs
Bug: If there is an incompatibility b/w the event data and the template, then we end up stalling the processing until the data/template is fixed.
Issue: When the above situation occurs, we throw an exception which is currently set to retry forever, thereby stalling the entire processing of the subsequent data. 
Fix: For such cases, we should log an error (which will be exposed to the customer), drop these events and continue processing the remaining events. 
(A longer-term solution that will prevent the customer from resending the rectified events is to have a dead letter queue where they can an action from for such dropped events.)
Changes include:
* Adding a custom exception to throw when there is incompatible data and we cannot evaluate the expression.
* Add a normalization exception …
=> fix: Incompatible event data does not cause normalization processing to stall

tools/data-mapper/Microsoft.Health.Tools.DataMapper.sln, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/package-lock.json, tools/data-mapper/Microsoft.Health.Tools.DataMapper/Microsoft.Health.Tools.DataMapper.csproj, tools/data-mapper/Microsoft.Health.Tools.DataMapper/Startup.cs
Fixed Data Mapper build errors and warnings:
- Added `package-lock.json`, with npm configured to use the npm public registry at https://registry.npmjs.org. As per https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json, "This file is intended to be committed into source repositories". Committing `package-lock.json` also fixes the following dependency error that occurred during "npm install":
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: microsoft.health.tools.datamapper@0.1.0
> npm ERR! Found: eslint@7.32.0
> npm ERR! node_modules/eslint
> npm ERR!   dev eslint@"^7.11.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from …
=> Data Mapper: Build error/warning fixes

tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/components/mapping/Detail.Forms.Fhir.Value.tsx, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/src/services/PersistService.ts
Fixed Data Mapper bugs:
- Specified a mapping's current device and FHIR mappings when renaming the mapping; otherwise undefined device and FHIR mappings get saved over the current ones. Fixes a bug where renaming a mapping's type name (either from the mapping page or from the home page) cleared all the Device Mapping and FHIR Mapping fields; when the user refreshed or navigated to the mapping page, the fields were shown empty.
- Corrected FhirValue property for Quantity. Fixes a bug where, when ValueType is "Quantity", adding or deleting a component cleared the Code, System, and/or Unit field(s).
=> Data Mapper: Bug fixes

docs/Configuration.md, src/lib/Microsoft.Health.Fhir.Ingest.Template/MeasurementExtractor.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/CalculatedFunctionContentTemplateTests.cs
We currently throw an exception if a required field is not present within the device event. This PR throws an exception when the field is supplied,  is `null` and is marked as required.
=> Throwing an exception if supplied field is null and is marked required

src/console/MeasurementCollectionToFhir/Processor.cs, src/console/Normalize/Processor.cs, src/console/Startup.cs
Bug: Operation field for Event metrics is being set with the default value Unknown through PaaS workflow.
Issue: As part of the nuget package update, the corresponding change in Startup.cs to set the connector operation was not also updated in the workspace plat code.
Fix: Instead of setting this context in the startup code in workspace plat, setting this value when instantiating the respective processors.
=> fix: Set connector operation for event metrics

build/build.yml, deploy/templates/consumption-azuredeploy.json, deploy/templates/default-managed-identity-azuredeploy.json, deploy/templates/premium-azuredeploy.json, src/console/Microsoft.Health.Fhir.Ingest.Console.csproj, src/console/appsettings.json, src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj, src/lib/Microsoft.Health.Common/Microsoft.Health.Common.csproj, src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj, src/lib/Microsoft.Health.Expressions/Microsoft.Health.Expressions.csproj, src/lib/Microsoft.Health.Extensions.Fhir.R4/Microsoft.Health.Extensions.Fhir.R4.csproj, src/lib/Microsoft.Health.Extensions.Fhir/Microsoft.Health.Extensions.Fhir.csproj, src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj, src/lib/Microsoft.Health.Fhir.Ingest.Schema/Microsoft.Health.Fhir.Ingest.Schema.csproj, src/lib/Microsoft.Health.Fhir.Ingest.Template/Microsoft.Health.Fhir.Ingest.Template.csproj, src/lib/Microsoft.Health.Fhir.Ingest.Validation/Microsoft.Health.Fhir.Ingest.Validation.csproj, src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj, src/lib/Microsoft.Health.Fhir.R4.Ingest/Microsoft.Health.Fhir.R4.Ingest.csproj, src/lib/Microsoft.Health.Logger/Microsoft.Health.Logging.csproj, test/Microsoft.Health.Common.UnitTests/Microsoft.Health.Common.UnitTests.csproj, test/Microsoft.Health.Events.UnitTest/Microsoft.Health.Events.UnitTest.csproj, test/Microsoft.Health.Expressions.UnitTests/Microsoft.Health.Expressions.UnitTests.csproj, test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/Microsoft.Health.Extensions.Fhir.R4.UnitTests.csproj, test/Microsoft.Health.Extensions.Fhir.UnitTests/Microsoft.Health.Extensions.Fhir.UnitTests.csproj, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/Microsoft.Health.Fhir.Ingest.Template.UnitTests.csproj, test/Microsoft.Health.Fhir.Ingest.UnitTests/Microsoft.Health.Fhir.Ingest.UnitTests.csproj, test/Microsoft.Health.Fhir.Ingest.Validation.UnitTests/Microsoft.Health.Fhir.Ingest.Validation.UnitTests.csproj, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Microsoft.Health.Fhir.R4.Ingest.UnitTests.csproj, test/Microsoft.Health.Tests.Common.R4/Microsoft.Health.Tests.Common.R4.csproj, test/Microsoft.Health.Tests.Common/Microsoft.Health.Tests.Common.csproj
**Code Changes:**
Migrated the projects below to .NET 6
- Microsoft.Health.Fhir.Ingest.Console
- Microsoft.Health.Events
- Microsoft.Health.Extensions.Fhir
- Microsoft.Health.Extensions.Fhir.R4
- Microsoft.Health.Extensions.Host
- Microsoft.Health.Fhir.Ingest
- Microsoft.Health.Fhir.Ingest.Validation
- Microsoft.Health.Fhir.R4.Ingest
- Microsoft.Health.Common.UnitTests
- Microsoft.Health.Events.UnitTests
- Microsoft.Health.Expressions.UnitTests
- Microsoft.Health.Extensions.Fhir.UnitTests
- Microsoft.Health.Extensions.Fhir.R4.UnitTests
- Microsoft.Health.Fhir.Ingest.UnitTests
- Microsoft.Health.Fhir.Ingest.Template.UnitTests
- Microsoft.Health.Fhir.Ingest.Validation.UnitTests
- Microsoft.Health.Fhir.R4.Ingest.UnitTests
Upgraded Azure functions from v3 to v4 
- …
=> .NET 6 Upgrade of Iot Connector Core Components

src/lib/Microsoft.Health.Fhir.Ingest.Template/AbstractJsonConverter.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/TemplateExtensions.cs
Follow Safe Deserialization practices and ensure type handling is disabled for Newtonsoft JSON serializers
=> Set Newtonsoft type handling to none

src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj
Function V4 requires minimum version of 4.3
[Functions V4 - Require a minimum version for supported extensions](https://github.com/Azure/Azure-Functions/issues/1987)
=> Update package version

tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/package-lock.json, tools/data-mapper/Microsoft.Health.Tools.DataMapper/ClientApp/package.json
Updated packages.
1. Updated local packages:
- **codemirror**
2. Updated **react-scripts** to the latest version to resolve dependencies' security vulnerabilities.
Result of updating **react-scripts**:
- Upgraded **ansi-regex** to version 5.0.1 or later, resolving [CVE-2021-3807](https://github.com/advisories/GHSA-93q8-gq69-wqmw)
- Upgraded **glob-parent** to version 5.1.2 or later, resolving [CVE-2020-28469](https://github.com/advisories/GHSA-ww39-953v-wcq6)
- Upgraded **browserslist** to version 4.16.5 or later, resolving [CVE-2021-23364](https://github.com/advisories/GHSA-w8qv-6jwh-64r5)
- Upgraded **immer** to version 9.0.6 or later, resolving [CVE-2021-3757](https://github.com/advisories/GHSA-c36v-fmgq-m8hx) and [CVE-2021-23436](https://github.com/advisories/GHSA-33f9-j839-rf8h)
- …
=> Data Mapper: Resolved package vulnerabilities

src/console/Microsoft.Health.Fhir.Ingest.Console.csproj, src/func/Microsoft.Health.Fhir.Ingest.Host/Microsoft.Health.Fhir.Ingest.Host.csproj
We currently have a transitive dependency on the deprecated package `Microsoft.Azure.DocumentDB.Core`. This is being pulled in from `Microsoft.Azure.WebJobs.Extensions.Storage -> Microsoft.Azure.Cosmos.Table -> Microsoft.Azure.DocumentDB.Core`. This PR upgrades our version of `Microsoft.Azure.WebJobs.Extensions.Storage` which no longer depends on `Microsoft.Azure.Cosmos.Table`.
Testing:
- Ran console app locally
- Ran Function Apps locally
=> Upgrade version of Webjobs Extension Storage

src/lib/Microsoft.Health.Common/Extension/StringExtensions.cs, src/lib/Microsoft.Health.Events/EventCheckpointing/StorageCheckpointClient.cs, src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj, src/lib/Microsoft.Health.Events/Model/EventMessage.cs, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/EventHubExceptionProcessor.cs, src/lib/Microsoft.Health.Extensions.Fhir/Microsoft.Health.Extensions.Fhir.csproj, src/lib/Microsoft.Health.Extensions.Host/Microsoft.Health.Extensions.Host.csproj, src/lib/Microsoft.Health.Fhir.Ingest.Validation/MappingValidator.cs, src/lib/Microsoft.Health.Fhir.Ingest.Validation/Microsoft.Health.Fhir.Ingest.Validation.csproj, src/lib/Microsoft.Health.Fhir.Ingest/Data/SampledDataProcessor.cs, src/lib/Microsoft.Health.Fhir.Ingest/Microsoft.Health.Fhir.Ingest.csproj
This PR updates the validation project to target netstandard as this is supported in the hosting service. 
Various changes were made throughout the codebase to become compliant with netstandard2.0
=> Downgrading Validation and transitive projects to netstandard2.0

src/lib/Microsoft.Health.Fhir.Ingest.Template/IotJsonPathContentTemplateFactory.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/IotJsonPathLegacyMeasurementExtractor.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/JsonPathExpressionEvaluatorFactory.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/LegacyMeasurementExtractor.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/MeasurementExtractor.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/TemplateExpressionEvaluatorFactory.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/IotJsonPathContentTemplateTests.cs, test/Microsoft.Health.Fhir.Ingest.Template.UnitTests/JsonPathContentTemplateTests.cs
This PR ensure that we throw a better exception when the `typeNameMatch` expression is not provided. Now, the following exception will be thrown: `An expression must be set for [TypeNameMatchExpression]`
=> Throw proper exception when TypeNameMatch expression is missing

src/lib/Microsoft.Health.Events/EventCheckpointing/ICheckpointClient.cs, src/lib/Microsoft.Health.Events/EventCheckpointing/StorageCheckpointClient.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/BaseEventProcessor.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/EventProcessor.cs
The previous checkpointing logic would use the StorageCheckpointOptions.CheckpointBatchCount property to wait until the specified number of checkpoint attempts occurred before actually recording a checkpoint. This can result in very infrequent checkpointing that will cause events to replay if the process is restarted.
There is already a batching mechanism in place that reduces the number of times a checkpoint is created, so this additional checkpoint delay is somewhat redundant. EventBatchingOptions.FlushTimespan and EventBatchingOptions.MaxEvents provide settings to the batching logic (at the event processing level) that dictate when a batch of events should be processed based on a time window or number of events in the batch. This PR updates the StorageCheckpoint Client to simply record …
=> Updated checkpointing logic to checkpoint after every event batch is processed

src/lib/Microsoft.Health.Extensions.Fhir.R4/Service/ResourceManagementService.cs
Revert deterministic id on Patient/Device create.  Found limitations on certain implementations of FHIR search.  Until those are resolved, reverting to original functionality.
=> Revert "Create patient resource using a deterministic id (#183)"

src/lib/Microsoft.Health.Fhir.Ingest/Template/FhirValueProcessor.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest.Templates/Template/CodeableConceptFhirValueProcessor.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest.Templates/Template/QuantityFhirValueProcessor.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest.Templates/Template/SampledDataFhirValueProcessor.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest.Templates/Template/StringFhirValueProcessor.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4FhirImportServiceTests.cs
* Add additional error information on existing type when merge value detect type mismatch.
* Add additional check to fail observation save if the observation found on the initial get doesn't contain the desired identifier.
=> Improve Observation Value Merge Type Mismatch Errors

src/func/Microsoft.Health.Fhir.Ingest.Host/IomtConnectorFunctions.cs, src/lib/Microsoft.Health.Extensions.Host/ConfigurationExtensions.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/JsonPathExpressionEvaluator.cs, src/lib/Microsoft.Health.Fhir.Ingest/Host/DeviceDataNormalizationExtensions.cs, src/lib/Microsoft.Health.Fhir.Ingest/Host/IngestWebJobsStartup.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementEventNormalizationService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/NormalizationDataMappingException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/NormalizationErrorHandlingPolicy.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/NormalizationServiceOptions.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/NormalizationExceptionTelemetryProcessor.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/MeasurementEventNormalizationServiceTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/NormalizationDataMappingExceptionTests.cs
- Add normalization error policy to control how exceptions during match & extract are handled
* Default is existing behavior, retry
* New option DiscardMatchAndExtractErrors, will emit errors as telemetry and continue.
- Errors during match & extract will be wrapped in a common exception type, NormalizationDataMappingException.
- Fixed minor formatting issue in JsonPathExpressionEvaluator leading to an extra $ in the exception messages.
- Added NormalizationErrorHandlingPolicy property to NormalizationServiceOptions.
- Updated DeviceDataNormalizationExtensions to include a factory for creating the NormalizationExceptionTelemetryProcessor based on the supplied settings (default is retry if none are configured).
=> Add normalization error policy

src/lib/Microsoft.Health.Fhir.Ingest.Template/CollectionTemplateFactory.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/LineInfo.cs, src/lib/Microsoft.Health.Fhir.Ingest.Template/TemplateErrorExtensions.cs, src/lib/Microsoft.Health.Fhir.Ingest.Validation/Extensions/IResultExtensions.cs, src/lib/Microsoft.Health.Fhir.Ingest.Validation/MappingValidator.cs, src/lib/Microsoft.Health.Fhir.Ingest.Validation/Models/ValidationError.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementEventNormalizationService.cs, src/lib/Microsoft.Health.Logger/ExceptionExtensions.cs, test/Microsoft.Health.Fhir.Ingest.Validation.UnitTests/MappingValidatorTests.cs
This PR makes several updates the Validation Result object returned during a mapping validation:
- Line numbers are returned when available
- Exceptions are split and returned as individual validation errors.
=> Enhance data returned in Validation Results

src/lib/Microsoft.Health.Fhir.Ingest.Template/MeasurementExtractor.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementEventNormalizationService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/Metrics/IomtMetricDefinition.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/Metrics/IomtMetrics.cs
This PR replaces #196 and only includes critical changes. This is because some of the work in #196 has been made redundant from other PRs.
=> Simplifying perf improvement PR

src/console/MeasurementCollectionToFhir/Processor.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/NormalizationEventConsumerService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/FhirExceptionTelemetryProcessor.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/Metrics/IomtMetrics.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/NormalizationExceptionTelemetryProcessor.cs, src/lib/Microsoft.Health.Logger/Telemetry/ExceptionTelemetryProcessor.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Telemetry/FhirExceptionTelemetryProcessorTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Telemetry/NormalizationExceptionTelemetryProcessorTests.cs
Bug: Unhandled exceptions and associated error metrics were being logged by the ExceptionTelemetryProcessor in addition to the logging done in the retry policy created for these operations.
Fix: Removed the logging from ExceptionTelemetryProcessor since the retry policy handles logging for a set of operations in addition to the event processing.
=> fix - Duplicate logging of unhandled/retryable exceptions.

src/console/Startup.cs, src/lib/Microsoft.Health.Common/IO/Compression.cs, src/lib/Microsoft.Health.Events/Model/EventMessage.cs, src/lib/Microsoft.Health.Events/Model/EventMessageFactory.cs, src/lib/Microsoft.Health.Events/Model/IEventMessage.cs, src/lib/Microsoft.Health.Fhir.Ingest/Config/MeasurementToEventMessageAsyncCollectorOptions.cs, src/lib/Microsoft.Health.Fhir.Ingest/Data/MeasurementToEventMessageAsyncCollector.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementFhirImportService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementGroupProcessingException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/FhirExceptionTelemetryProcessor.cs, test/Microsoft.Health.Common.UnitTests/Microsoft.Health.Common.UnitTests.csproj, test/Microsoft.Health.Events.UnitTest/EventBatchingTests.cs, test/Microsoft.Health.Events.UnitTest/EventConsumerServiceTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Data/MeasurementToEventMessageAsyncCollectorTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Microsoft.Health.Fhir.Ingest.UnitTests.csproj, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/MeasurementFhirImportServiceTests.cs, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Microsoft.Health.Fhir.R4.Ingest.UnitTests.csproj, test/Microsoft.Health.Tests.Common/Microsoft.Health.Tests.Common.csproj
Summary of changes
Normalization
- Add ability to compress the measurementGroup and send the compressed measurementGroup.
- Add way to flag if we are sending a measurement or measurementGroup (set IsMeasurementGroup property)
- Add way to flag if we are sending a compressed event payload (set ContentType to application/gzip)
- The compression on the normalization side is off by default, since we would like to first support it on the MeasurementToFhir side first
MeasurementToFhir
- Detect if event batch contains measurements, measurementGroups, or both
- Add ability to process any of the above, or combinations of the above
- Add ability to decompress event payload if it is compressed
=> Add compression support

src/lib/Microsoft.Health.Events/EventCheckpointing/StorageCheckpointClient.cs, src/lib/Microsoft.Health.Events/Model/Checkpoint.cs, src/lib/Microsoft.Health.Events/Model/EventMessageFactory.cs
We currently do not store message offset or sequence number inside of our checkpoint file. This information is needed to accurately calculate the event processing backlog. This PR adds this information as metadata in our checkpoint file. It also address a bug where we were passing message offset as message sequence number, and vise versa.
=> Store event offset and sequence number in Checkpoint

src/lib/Microsoft.Health.Extensions.Fhir.R4/BundleExtensions.cs, src/lib/Microsoft.Health.Extensions.Fhir/MultipleResourceFoundException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementFhirImportService.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/MeasurementFhirImportServiceTests.cs
- Update MultipleResourceFoundException to include optional collection of ids that will be included in the error message.
- Add logic to R4FhirImportService to not immediately fail if multiple Observations are return.  Attempt to find only one observation in the returned collection that matches the desired identifier. If multiple observations still exist throw the expection as normal.
- Add method, GetMeasurementKey, to ensure same logic is used for generating keys for measurement grouping.
=> Add attempt to resolve a single observation when FHIR server returns multiple records in a bundle

src/lib/Microsoft.Health.Events/EventHubProcessor/BaseEventProcessor.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/EventProcessor.cs, src/lib/Microsoft.Health.Events/Resources/EventResources.Designer.cs, src/lib/Microsoft.Health.Events/Resources/EventResources.resx, src/lib/Microsoft.Health.Events/Telemetry/Exceptions/EventHubExceptionProcessor.cs
The recommended way to read from Event Hub from production workloads is using the [EventProcessorClient](https://docs.microsoft.com/en-us/azure/event-hubs/event-processor-balance-partition-load). This utilizes blob storage to manage ownership and partition balancing. The iomt-fhir project current using the EventProcessorClient to connect to Event Hub.
However there are also other ways to read from Event Hub. When reading from an Event Hub using the [EventHubConsumerClient](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.consumer.eventhubconsumerclient?view=azure-dotnet) (not recommended for production) or the [EventHubClient (legacy)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.eventhubclient.createepochreceiver?view=azure-dotnet) it is …
=> Handle case where an event reader with epoch ownership is connected

src/lib/Microsoft.Health.Events/EventConsumers/Service/EventBatchingService.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/EventConsumerService.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/IEventConsumerService.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/BaseEventProcessor.cs, test/Microsoft.Health.Events.UnitTest/EventBatchingTests.cs
There is a bug where we can read from a partition, then lose partition ownership to a another reader, then regain ownership. In the case where we regain ownership it is possible for previous events to exists in the event batching queues for that partition (from the previous point in time when reader had ownership). This is a problem because the next event read will flush the queue with the old events and update the checkpoint with the timestamp of the last old event. 
In the case where we regain partition ownership we should delete any previous knowledge/events, and start reading from the checkpoint provided. This PR ensures that the queue in cleared (deleted) when we begin reading from a partition so that it is not possible to retain any old events.
=> Reset batch queues when partition initialized

src/lib/Microsoft.Health.Events/Microsoft.Health.Events.csproj
Eventhub SDK 5.7.1 introduced a [regression]([https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.EventHubs_5.7.2/sdk/eventhub/Azure.Messaging.EventHubs/CHANGELOG.md - bugs-fixed](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.EventHubs_5.7.2/sdk/eventhub/Azure.Messaging.EventHubs/CHANGELOG.md#bugs-fixed)) where the PartitionKey was not being used. This results in Measurements not landing on the same partition, which has undesired effects in downstream processing. This PR bumps the nuget version where the issue has been resolved.
=> Address regression in 5.7.1 by bumping to 5.7.2

src/lib/Microsoft.Health.Extensions.Fhir.R4/Microsoft.Health.Extensions.Fhir.R4.csproj, src/lib/Microsoft.Health.Extensions.Fhir.R4/Search/SearchExtensions.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs, test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/SearchExtensionsTests.cs
This PR updates the way MeasurementToFhir operations search for Observations that might already exist because data is being updated or resubmitted. Instead of searching using the identifier, the identifier is split into components (patient resource id, device resource id, typeName or code, start date and end date) a query string is generated using the individual components and used to make a search request on the FHIR service.
=> Expand identifier search parameters for Observation resources

src/console/Microsoft.Health.Fhir.Ingest.Console.csproj, tools/data-mapper/Microsoft.Health.Tools.DataMapper/Microsoft.Health.Tools.DataMapper.csproj
CVE-2021-24112
A remote code execution vulnerability exists when parsing certain types of graphics files. This vulnerability only exists on systems running on MacOS or Linux. This CVE ID is unique from CVE-2021-26701.
Upgrade System.Drawing.Common from 4.7.0 to 4.7.2 to fix the vulnerability.
=> Address component vulnerability

Microsoft.Health.Fhir.Ingest.sln, src/lib/Microsoft.Health.Extensions.Fhir.R4/BundleExtensions.cs, src/lib/Microsoft.Health.Extensions.Fhir.R4/ResourceExtensions.cs, src/lib/Microsoft.Health.Extensions.Fhir/IResourceMetadata.cs, src/lib/Microsoft.Health.Extensions.Fhir/MultipleResourceFoundException.cs, src/lib/Microsoft.Health.Extensions.Fhir/ResourceMetadata.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs
* Update MultipleResourceFound exception to also include the version and last updated data in addition to the internal id.
* Fix issue with solution & Legacy library.
=> Include version and update datetime on MultipleResourceFound exceptions

src/lib/Microsoft.Health.Events/EventCheckpointing/StorageCheckpointClient.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/BaseEventProcessor.cs
For task cancelled exceptions, we are now logging a trace instead of an error.
=> Handle task cancelled exceptions

src/lib/Microsoft.Health.Events/EventConsumers/Service/EventBatchingOptions.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/EventBatchingService.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/EventConsumerService.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/IEventConsumerService.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/Infrastructure/EventPartition.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/BaseEventProcessor.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/EventProcessor.cs
For the FHIR transformation there are some performance gains from scaling out and increasing the batch size. Currently the batch size is static but as we scale out (think 1 partition per application instance) then we technically have more memory and can increase the batch size. This will result in fewer FHIR application calls (assuming most of the data is for once device, which often is the case for needing to scale out) and will increase throughput.
The PR allows a variable to be set called `EventBatching__MaxEventsAllPartitions` which allows the user to specify the maximum events we should process across all the partitions. If this variable is set, and we are processing only 1 partition for example, then the number of events specified in EventBatching__MaxEventsAllPartitions will be the …
=> Adapt batch size when horizontal scaling enabled

tools/data-mapper/Microsoft.Health.Tools.DataMapper/Microsoft.Health.Tools.DataMapper.csproj
Addresses component governance alert CVE-2022-41032 in NuGet.Protocol 5.11.0. Severity: High
Explicitly reference the Nuget.Protocol package to force a version > 5.11. The previous upgrade of root package Microsoft.VisualStudio.Web.CodeGeneration.Design wasn't enough.
=> Address CVE-2022-41032 in Data Mapper

src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs
Switch FhirImportService back to normal identifier search parameter instead of the expanded search parameters.  Discovered expanded search parameters generate more complex and long running queries on the FHIR service side (50 ms vs > 1 second) severely impacting performance.
This reverts #240
=> Switch FhirImportService back to normal identifier search parameter

src/lib/Microsoft.Health.Fhir.Ingest.Template/TemplateNotFoundException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Exceptions/CorrelationIdNotDefinedException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Exceptions/InvalidDataFormatException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Exceptions/InvalidQuantityFhirValueException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Exceptions/NormalizationDataMappingException.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/FhirDataMappingException.cs
It would be helpful to customers to make a few more exceptions customer-facing (emitted in logs).
TemplateNotFoundException 
CorrelationIdNotDefinedException 
InvalidDataFormatException 
InvalidQuantityFhirValueException 
NormalizationDataMappingException 
FhirDataMappingException
=> Add additional exceptions to be surfaced as logs

src/console/Program.cs
Recent host image change in AKS has lead to following error:
```
Unhandled exception. System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
```
Disabling reloadOnChange for configurations to prevent this issue.
=> Disable reloadOnChange for MedTech configurations

src/lib/Microsoft.Health.Fhir.Ingest/Service/NormalizationEventConsumerService.cs
When normalizing a device message there are some exceptions that can be thrown in [template.GetMeasurements(token)](https://github.com/microsoft/iomt-fhir/blob/36ea37f11f09e2e6cdfad167be48be91b62d0091/src/lib/Microsoft.Health.Fhir.Ingest/Service/NormalizationEventConsumerService.cs#L213). 
For example, if a user specifies a timestamp expression below and `matchedToken.pathNotFoundInDeviceMessage` resolves to null, then an exception is thrown internally: "System.Exception Error: invalid-type, function fromUnixTimestampMs expects argument 0 to be one of the following: Integer"
```json
"timestampExpression": {
"value": "fromUnixTimestampMs(matchedToken.pathNotFoundInDeviceMessage)",
"language": "JmesPath"
},
```
In this Pull Request we are adjusting the try/catch block to capture any …
=> Catch additional normalization mapping exceptions

src/console/MeasurementCollectionToFhir/Processor.cs, src/console/Microsoft.Health.Fhir.Ingest.Console.Common/FhirTransformation/Processor.cs, src/lib/Microsoft.Health.Events/EventCheckpointing/ICheckpointClient.cs, src/lib/Microsoft.Health.Events/EventCheckpointing/StorageCheckpointClient.cs, src/lib/Microsoft.Health.Events/EventConsumers/EventPrinter.cs, src/lib/Microsoft.Health.Events/EventConsumers/IEventConsumer.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/EventBatchingService.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/EventConsumerService.cs, src/lib/Microsoft.Health.Events/EventConsumers/Service/IEventConsumerService.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/BaseEventProcessor.cs, src/lib/Microsoft.Health.Extensions.Fhir.R4/SHA256HashGenerator.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/FhirImportService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/IFhirImportService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/IImportService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementFhirImportService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementGroupFhirImportService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/NormalizationEventConsumerService.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/Metrics/IomtMetricDefinition.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/Metrics/IomtMetrics.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs, test/Microsoft.Health.Events.UnitTest/EventBatchingTests.cs, test/Microsoft.Health.Events.UnitTest/EventConsumerServiceTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/FhirImportServiceTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/MeasurementFhirImportServiceTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/MeasurementGroupFhirImportServiceTests.cs, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4FhirImportServiceTests.cs
In order to prevent duplicate observations from being created, we will be changing two things.
1. Pass cancellation tokens through to downstream methods. If an event processor loses ownership of a partition we should receive a cancellation token and pass this cancellation token to our fhir import service and stop any additional requests.
2. While cancellations are a good start, they do not necessarily handle in flight requests. So in addition, when creating an observation, we should not let the server generate the observation id. Previously, when two processors were writing to the fhir service it was possible that two creates could happen at the same time which would result in 2 observations. In this pull request the client (medtech service) will hash the id so that the id is …
=> Prevent duplicate observations from being created

src/lib/Microsoft.Health.Events/EventConsumers/Service/EventBatchingService.cs, src/lib/Microsoft.Health.Events/Telemetry/Metrics/EventMetricDefinition.cs, src/lib/Microsoft.Health.Events/Telemetry/Metrics/EventMetrics.cs
Added freshness delay metric and logic for it to be invoked in the case of a healthy service (i.e. if a large freshness delay were to be reported after these changes, we would expect it to be due to a large volume of events, rather than an issue with the service itself). The next iteration of this work will involve adding logic to invoke this metric in the case where processing fails, leading to a backlog of events to process.
**Testing**
Provisioned a MedTech service in my personal cluster and observed the metric flowing through as expected.
=> Add freshness delay metric

src/lib/Microsoft.Health.Fhir.Ingest/Data/SampledDataProcessor.cs, src/lib/Microsoft.Health.Fhir.Ingest/Service/MeasurementFhirImportService.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Data/SampledDataProcessorTests.cs, test/Microsoft.Health.Fhir.Ingest.UnitTests/Service/MeasurementFhirImportServiceTests.cs
Changes include two fixes:
* When multiple messages that contain data for the same Observation have the same timestamp, the measurement data in the first message processed is the only data persisted. 
Fix includes taking the latest event data for the same timestamp within the batch and only adding the corresponding measurement in the measurement group.
* When merging sampled data (new data with an existing observation), if the timestamp between the new and the existing value collides, the existing value was being taken which resulted in the merged observation not being considered for an 'update'. 
Fix includes taking the new data value if there is timestamp collision so that merged observation represents latest data.
=> Fix event/observation updates being dropped

src/lib/Microsoft.Health.Common/Telemetry/MetricExtension.cs, src/lib/Microsoft.Health.Common/Telemetry/Metrics/Dimensions/DimensionNames.cs, src/lib/Microsoft.Health.Fhir.Ingest/Telemetry/Metrics/IomtMetrics.cs, test/Microsoft.Health.Common.UnitTests/MetricExtensionTest.cs
The FHIRResourceContention metric was adding a dimension called 'Name' via .AddDimension but the metric extension method .CreateBaseMetric also adds a dimension called 'Name', so the end result was the 'Name' dimension was added twice which resulted in an exception the second time 'Name' was added to the metric dimensions dictionary.
Updated the FHIRResourceContention metric to use a different dimension name for the FHIR resource so that the 'Name' dimension isn't added twice.
Also updated the metric extension class so that when .AddDimension is called and there is already a dimension with that name we no longer throw an exception and instead log an error trace. The dimension is not added/overwritten.
=> Fix duplicate dimension being added

src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs
Previously we checked the FHIR resource version after creating an Observation to see if the version equaled "1". If the version did not equal "1" we logged an error and a metric and continued on. This was so we had enough information on when two processes were potentially modifying an Observation at the same time. Now that we know the cause we can remove the error logging which is not needed, but we are going to keep the metric just in case. In addition we also happened to notice that there were some false positives with the error logging and metric logging. We noticed that soft-deleted resources that are recreated do not have a version equal to "1" when they are recreated, which was causing an error to be logged even though there was no resource contention. This was a missed case and …
=> Ignore FHIR version check on soft delete

docs/CustomFunctions.md
Various updates to documentation. Being more explicit about needing to specify the expression language type as JmesPath. Also calling out the need to escape literal values. This is inside of JmesPath documentation but its useful to copy that here.
=> Edit custom function docs

src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientCreateIdentityService.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientLookupIdentityService.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientWithEncounterLookupIdentityService.cs, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4DeviceAndPatientCreateIdentityServiceTests.cs, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4DeviceAndPatientLookupIdentityServiceTests.cs
Update the IdentityService to always link and encounter id if specified in the measurement group.
This will allow optional encounter linking in the LookupIdentityService & CreateIdentityService.
The DeviceAndPatientWithEncounterIdentityService will still require the encounter id present or a ResourceIdentityNotDefinedException will be thrown.
=> Support optional encounter linking in Lookup & Create

src/lib/Microsoft.Health.Extensions.Fhir.R4/IdentifierExtensions.cs, src/lib/Microsoft.Health.Extensions.Fhir.R4/Service/ResourceManagementService.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4DeviceAndPatientCreateIdentityService.cs, src/lib/Microsoft.Health.Fhir.R4.Ingest/Service/R4FhirImportService.cs, test/Microsoft.Health.Common.UnitTests/Utilities.cs, test/Microsoft.Health.Extensions.Fhir.R4.UnitTests/Service/ResourceManagementServiceTests.cs, test/Microsoft.Health.Fhir.R4.Ingest.UnitTests/Service/R4DeviceAndPatientCreateIdentityServiceTests.cs
[Address Github issue](https://github.com/microsoft/iomt-fhir/commit/31c0130ed019dc0c1854f17ef9c11b39783ca69a) https://github.com/microsoft/iomt-fhir/issues/188 
Support deterministic device and patient ids in create mode to avoid duplicates.
Switch device and patient logic to use deterministic ids based on the identifiers. Instead of using Create so the service sets the resource id, the id will be set and the Update path used (necessary per FHIR spec to set the resource id).  Logic now mirrors a recent change made to Observations.
- Added unit tests for ResourceManagementService.
- Added additional test helper extensions for IFhirService mocks for common test scenarios.
- Updated R4DeviceAndPatientCreateIdentityServiceTests to validate ids generated for resources are derived from the …
=> Address Issue 188

docs/ARMInstallation.md
The URL for the site that hosted the "Deploy to Azure" button appears to no longer a have a valid SSL certificate which unfortunately means that the button does not show up when viewing the [ARM Installation page](https://github.com/microsoft/iomt-fhir/blob/main/docs/ARMInstallation.md) :(
The old hosting location was: https://azuredeploy.net/deploybutton.png
[These docs](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-azure-button) say to use https://aka.ms/deploytoazurebutton so this PR updates to URL to the new location.
=> fix "Deploy to Azure" button

src/lib/Microsoft.Health.Events/EventHubProcessor/BaseEventProcessor.cs
Previously the iot connector would begin reading from a partition based on the last checkpointed event's enqueued time. The date compassion used `EventPosition.FromEnqueuedTime(checkpoint.LastProcessed)` was inclusive, meaning that the last checkpointed event was included in the first batch on initialization. This is not desirable because it reprocesses one event on shutdown/startup or when partition ownership is lost, which is unnecessary. Reprocessing this one event also causes issues with the data freshness calculations since the reprocess of an older event makes it seem like the iot connector had fallen behind.
There are options to instead use the event offset or the event sequence id to resume processing events from a checkpoint. Since we already store the event offset and sequence …
=> Initialize event hub partition reading from the next event after the checkpoint

src/lib/Microsoft.Health.Events/EventHubProcessor/IResumableEventProcessor.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/ResumableAssignedPartitionProcessor.cs, src/lib/Microsoft.Health.Events/EventHubProcessor/ResumableEventProcessor.cs
The `ResumeAsync` method will restart processing if the EventProcessorClient is not already running. This PR returns an indication of when the method has started the processor.
This indication will support downstream health checks.
=> Return an indicator when we resume the processor
